### ISSUE TITLE
BFC & IFC

### ISSUE THREAD

**Issue by sup-fiveyear** [sup-fiveyear/Notes#5]
### 常见定位方式：

* 普通文本流
元素按照在HTML文档中自上而下的进行布局，对于行内元素水平排列，空间占满后会自动换行。对于块级元素会被渲染成完整的新行。默认情况下所有元素都是按照普通文本流进行布局，位置由元素在HTML中的书写位置决定。
* 浮动流
元素首先按照普通流的位置出现，根据浮动的方向尽可能靠左或者靠右，类似印刷排版中的文本环绕。
* 绝对定位流
元素脱离文本流，定位元素不会对兄弟元素造成影响，元素的位置由坐标的位置决定。

###  **BFC的概念：** 
块级格式上下文是页面中的一块渲染区域，有着自己一套渲染规则，他决定了子元素**如何定位**、**和其他元素之间的关系**以及相互之间的作用。

属于定位方案中的普通流，将BFC理解为**结界，容器里面的元素在布局上不会影响到外部的元素，并且具有普通元素没有的特性**

**触发BFC：** 
* body根元素
* 浮动元素
* 绝对定位元素
* dispaly:inline-block, table,flex
* overflow:hidden,auto,scroll

**渲染规则**

* 块盒的渲染特点~
* 垂直margin合并
* 隔离的独立容器
* 计算高度，浮动元素参与计算

**应用：** 
1. 解决外边距重叠
```css
<head>
div{
    width: 100px;
    height: 100px;
    background: lightblue;
    margin: 100px;
}
</head>
<body>
    <div></div>
    <div></div>
</body>
```
![26DEA29D-5F4A-45F9-ACC4-BEA0DF807320](https://user-images.githubusercontent.com/53052047/79854203-ae265880-83fb-11ea-8297-94f8cd616b18.png)

将他们放置在不同BFC中，能够解决外边距重叠

```css
<div class="container”>
    <p></p>
</div>
<div class=“container”>
    <p></p>
</div>
```

```css
.container {
    overflow: hidden;
}
p {
    width: 100px;
    height: 100px;
    background: lightblue;
    margin: 100px;
}
```

![09E48426-4CF6-4A8D-A9F2-4BFC132C14CE](https://user-images.githubusercontent.com/53052047/79854228-baaab100-83fb-11ea-9a44-d6554bf18599.png)

2. BFC可以包含浮动的元素（清除浮动）

```css
<div style=“border: 1px solid #000;”>
    <div style=“width: 100px;height: 100px;background: #eee;float: left;”></div>
</div>
```

[image:395B0E88-23BB-47F5-91ED-91F18510E35A-66052-0000FD2634A8307E/870FE6CC-A701-4830-9041-AD95A585A59B.png]

由于容器内部元素浮动，造成脱离文本流，所以容器只剩下border的高度，如果让容器触发BFC，那么容器将会包裹着浮动元素

```css
<div style="border: 1px solid #000;overflow: hidden”>
    <div style=“width: 100px;height: 100px;background: #eee;float: left;”></div>
</div>
```
![870FE6CC-A701-4830-9041-AD95A585A59B](https://user-images.githubusercontent.com/53052047/79854248-c1d1bf00-83fb-11ea-867a-cd3eb1ee8ee1.png)

3. 防止元素被浮动元素覆盖

```css
<div style="height: 100px;width: 100px;float: left;background: lightblue”>我是一个左浮动的元素</div>
<div style=“width: 200px; height: 200px;background: #eee”>我是一个没有设置浮动, 
也没有触发 BFC 元素, width: 200px; height:200px; background: #eee;</div>
```

![D58AB456-DC54-4C4C-B200-795764F18218](https://user-images.githubusercontent.com/53052047/79854261-c6967300-83fb-11ea-874c-2b3532581ba9.png)

能够看到灰色容器被浮动元素覆盖，因此可以让灰色容器触发BFC，使得让他不受到外界元素的渲染干扰。
![609899FA-5B33-4E6B-B29C-A943A41DC3AE](https://user-images.githubusercontent.com/53052047/79854324-dca43380-83fb-11ea-83a5-1b79073824e0.png)

> 可以使用该方法实现两栏自适应布局，左边固定宽度，右边自适应宽度

### IFC

当行容器盒（inline container box）不包括任何块级盒（block-level boxes）时，就会创建一个行内格式化上下文（IFC）。

#### 渲染规则

* 水平铺满，容器不够会换行
* 每行生成一个匿名行包裹所有行盒
* 水平方向，对齐方式由text-align属性来决定（所有盒子的宽度小于最大宽度时）
* 垂直方向，对齐方式vertical-align控制，默认baseline
* 实际宽度由内部元素控制，不受border padding margin 的影响

> 对齐基线无法O(1)时间总结出来

----
*对齐基线的规则*
